In [1]:
"""
TO DO:
    covariance function
        -sqrexp & sqrexpf
            -with and without embedding ***
    covariance function derivative
        -sqrexp & sqrexpf
            -with and without embedding
    rprop
        -not sure how to do this
        -maybe take a system for which we know optimal params and see if it gets there
    liklihood & gradient & predict
        -carefully verify formulas are correct
    test priors
        -make sure they are applied properly
    
"""

'\nTO DO:\n    covariance function\n        -sqrexp & sqrexpf\n            -with and without embedding ***\n    covariance function derivative\n        -sqrexp & sqrexpf\n            -with and without embedding\n    rprop\n        -not sure how to do this\n        -maybe take a system for which we know optimal params and see if it gets there\n    liklihood & gradient & predict\n        -carefully verify formulas are correct\n    test priors\n        -make sure they are applied properly\n    \n'

In [1]:
import numpy as np
import KenGP as gp

In [2]:
X = np.array([[1,0,0,1],[2,3,4,2]]).T
Y = np.array([[1,2,3,4]]).T
print("Expected\n", X,"\n", Y)
gp.setData(X,Y)
print("Result\n", gp.X,"\n", gp.Y)

Expected
 [[1 2]
 [0 3]
 [0 4]
 [1 2]] 
 [[1]
 [2]
 [3]
 [4]]
Data input success
Result
 [[1 2]
 [0 3]
 [0 4]
 [1 2]] 
 [[1]
 [2]
 [3]
 [4]]


In [3]:
# covar with no embedding
print("Hyperparamaters ",gp.hp)
print("covar(",gp.X[2],",",gp.X[3],")")
print("Expected ", 0.060653)
print("Result ",gp.covar(gp.X[2],gp.X[3],2,3,1))

print("\ndCovardHP")
for i in range(0,3):
    print("dCdHP[",i,"]=",gp.dCovardHp(2,3,i))

Hyperparamaters  [0.1 0.1 0.1]
covar( [0 4] , [1 2] )
Expected  0.060653
Result  0.06065306597126335

dCovardHP
dCdHP[ 0 ]= -0.3032653298563167
dCdHP[ 1 ]= 0.6065306597126334
dCdHP[ 2 ]= -0.3032653298563167


In [4]:
# embedding basics
gp.setTimeDelayInterval(1)
print(gp.X)
gp.setTimeDelayEmbedding([1,1])
correct = np.array([[0,4,0,2],[1,2,0,3]])
print("Expected\n", correct)
print("Result\n", gp.X)

if np.array_equal(gp.r,np.array([10**-10,1])):
    print("r is calculated correctly.")
else: 
    print("r is not calculated correctly: ",gp.r)

[[1 2]
 [0 3]
 [0 4]
 [1 2]]
tmp  (4, 4)
r  [1.e-10 1.e+00]
Prior dict  {0: 'none', 1: 'none', 2: 'none', 3: 'none', 4: 'none'}
New X Dimensions  (2, 4)
Expected
 [[0 4 0 2]
 [1 2 0 3]]
Result
 [[0. 4. 0. 2.]
 [1. 2. 0. 3.]]
r is calculated correctly.


In [5]:
print("Hyperparamaters ",gp.hp)
print("covar(",gp.X[0],",",gp.X[1],") ")
print("Expected ", 0.05488)
print("Result ", gp.covar(gp.X[0],gp.X[1],0,1,1))

gp.setHP([2, 0.5, 1, 3, 4])
print("\nHyperparamaters ", gp.hp)
print("covar(",gp.X[0],",",gp.X[1],") ")
print("Expected ", 0.0000617)
print("Result ", gp.covar(gp.X[0],gp.X[1],0,1,1))

Hyperparamaters  [0.1 0.1 0.1 0.1 0.1]
covar( [0. 4. 0. 2.] , [1. 2. 0. 3.] ) 
Expected  0.05488
Result  0.05488116360940264
Hp:  [2, 0.5, 1, 3, 4]

Hyperparamaters  [2, 0.5, 1, 3, 4]
covar( [0. 4. 0. 2.] , [1. 2. 0. 3.] ) 
Expected  6.17e-05
Result  6.170490204333977e-05


In [6]:
print("\ndCovardHP on ",gp.X[0],gp.X[1])
expected = [0,1.234*(10**-4),-3.085*(10**-4),0,6.170*(10**-5)]
for i in range(1,5):
    print("Expected = ", expected[i])
    print("dCdHP[",i,"]=",gp.dCovardHp(0,1,i))


dCovardHP on  [0. 4. 0. 2.] [1. 2. 0. 3.]
Expected =  0.00012340000000000002
dCdHP[ 1 ]= 0.00012340980408667953
Expected =  -0.0003085
dCdHP[ 2 ]= -0.0003085245102166989
Expected =  0
dCdHP[ 3 ]= -0.0
Expected =  6.170000000000001e-05
dCdHP[ 4 ]= -6.170490204333977e-05


In [8]:
gp.setCovar("sqrexpf")
gp.setTimeDelayEmbedding( [0, 0] )
gp.setHP([0,0.6,0.25,0.5])


i1, i2 = (1, 3)
print("Expected ", 0.25733,"\nActual ",gp.covar(gp.X[i1], gp.X[i2], i1, i2, abs(i1-i2)))

exp = [0.4289,-0.5147,-0.1287]
for h in range(1,4):
    print("Hyperparam ", h, " = ",gp.dCovardHp(i1,i2,h), " actual ", exp[h-1])


Prior dict  {0: 'none', 1: 'none', 2: 'none', 3: 'none', 4: 'none', 5: 'none'}
Covariance function set to  sqrexpf
Prior dict  {0: 'none', 1: 'none', 2: 'none', 3: 'none', 4: 'none', 5: 'none'}
Hp:  [0, 0.6, 0.25, 0.5]
Expected  0.25733 
Actual  0.25732916548821205
Hyperparam  1  =  0.42888194248035344  actual  0.4289
Hyperparam  2  =  -0.5146583309764241  actual  -0.5147
Hyperparam  3  =  -0.12866458274410603  actual  -0.1287
